FROM quay.io/ncigdc/bio-u18:latest

MAINTAINER Charles Czysz <czysz@uchicago.edu>

ARG VERSION

ENV PICARD_URL=https://github.com/broadinstitute/picard/releases/download/${VERSION}/picard.jar

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
       openjdk-11-jre-headless \
       r-base \
       wget \
    && wget -O /usr/local/bin/picard.jar $PICARD_URL \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
